services: 
  frontend:
    image: morsultra/deliverable3:frontend
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/react-app
      - /react-app/node_modules
    environment:
      - WATCHPACK_POLLING=true 
    depends_on:
      - db

  backend: 
    image: morsultra/deliverable3:backend
    build: 
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "5000:5000"
    volumes: 
      - ./backend:/app
    environment:
      FLASK_DEBUG: 1
    depends_on: 
      - db
  db: 
    image: mysql:8.3
    restart: always
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: deliverable3_testing_db
    ports: 
      - "3306:3306"
    volumes: 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql