services: 
  frontend: 
    image:
      context: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/react-app
      - /react-app/node_modules
    environment:
      - WATCHPACK_POLLING=true 

  backend: 
    build: 
      context: ./backend
    ports: 
      - "5000:5000"
    volumes: 
      - ./backend:/app
    depends_on: 
      - db

  db: 
    image: mysql:8.3
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: example
    ports: 
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes: 
  db_data: