name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker dev images
      run: docker compose build
      
    - name: Start Docker dev images
      run: docker compose up -d

    - name: Show Docker containers
      run: docker container ls && docker network ls && docker network inspect deliverable3-dev_default


    - name: Run backend tests
      run: docker exec backend pytest -s tests/
