name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4

    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build Docker dev images
    #   run: docker compose -f docker-compose-prod.yml build

    # - name: Push Docker images
    #   run: docker compose -f docker-compose-prod.yml push
      
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker compose -f docker-compose-prod.yml down -v
          docker compose -f docker-compose-prod.yml pull
          docker compose -f docker-compose-prod.yml up -d


